/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    introduction: [{ type: "autogenerated", dirName: "introduction" }],
    application: [{ type: "autogenerated", dirName: "application" }],
    provisioning: [{ type: "autogenerated", dirName: "provisioning" }],
    runtime: [{ type: "autogenerated", dirName: "runtime" }],
    orchestration: [{ type: "autogenerated", dirName: "orchestration" }],
    observability: [{ type: "autogenerated", dirName: "observability" }],
};

module.exports = sidebars;